# Site settings
title: Hardware Club episode show notes
email: hello@hardwareclub.io
description: >
  Shownotes for every Hardware Club episode.
baseurl: "/shownotes" # the subpath of your site, e.g. /blog/
url: "localhost:3000" # the base hostname & protocol for your site
permalink: /:title/_notes.html

twitter_username: juliancheal
github_username:  juliancheal

exclude: ["about", "css", "feed", "index"]

defaults:
  -
    values:
      layout: "rails"

sass:
  sass_dir: _sass
  style: :compressed

destination: /Users/Jools/Documents/Projects/Robots/Hardwareclub.io/hardwareclub/app/views/shownotes

# Build settings
markdown: kramdown
kramdown:
  input: GFM
